[package]
name = "ivyterm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "2.3.1"
glib = "0.20.0"
gtk4 = { version = "0.9.0", features = ["v4_10"] }
lazy_static = "1.5.0"
libadwaita = "0.7.0"
log = "0.4.22"
vte4 = "0.8.0"

