[package]
name = "ivyterm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.19.5"
gtk4 = { version = "0.8.2", features = ["v4_12"] }
lazy_static = "1.4.0"
libadwaita = "0.6.0"
vte4 = { version = "0.7.1", features = ["v0_74"] }
