font = "CommitMono weight=400 13"
scrollback_lines = 500

foreground = "#ffffff"
background = "#000000"

standard_colors = [
    "#2e3436",
    "#cc0000",
    "#4e9a06",
    "#c4a000",
    "#3465a4",
    "#75507b",
    "#06989a",
    "#d3d7cf",
]
bright_colors = [
    "#555753",
    "#ef2929",
    "#8ae234",
    "#fce94f",
    "#729fcf",
    "#ad7fa8",
    "#34e2e2",
    "#eeeeec",
]

[keybindings]
new_tab = "<Ctrl><Shift>t"
close_tab = "<Ctrl><Shift>w"
split_horizontal = "<Ctrl><Shift>o"
split_vertical = "<Ctrl><Shift>l"
close_pane = "<Ctrl><Shift>d"
toggle_zoom = "<Ctrl><Shift>x"
copy_selection = "<Ctrl><Shift>c"
move_right = "<Alt>Right"
move_left = "<Alt>Left"
move_up = "<Alt>Up"
move_down = "<Alt>Down"
